### ISSUE TITLE
#bots create.lnuser - error when removing a large list of jobs

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#113]
```cmd
2021-01-14 12:18:03:  > Remove currents jobs...
2021-01-14 12:19:13:  >  > Reporting login failure (unknown): unable to locate element, using {:data_control_name=>"edit_position", :tag_name=>"a", :index=>0}
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:536:in `assert_element_found'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:508:in `assert_exists'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:358:in `fire_event'
C:/code/bots/lib/linkedin/bots/LinkedInWriteProfile.rb:78:in `write'
C:/code/bots/lib/pampa/CreateLnUserProcess.rb:437:in `process'
C:/code/bots/cli/create.linkedin.rb:64:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.16/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.19/lib/browserfactory.rb:247:in `run'
C:/code/bots/cli/create.linkedin.rb:186:in `<main>'... done
2021-01-14 12:19:15:  >  > Tracking bot error... done
2021-01-14 12:19:16:  >  > Ping to Division... done
2021-01-14 12:19:31:  >  > Sleep for long time. Click CTRL+C to exit and close any opened browser... 2021-01-14 12:23:57: Interrupt signal on MyBotProcess! 
```

**Comment by leandrosardi** [comment]
Fixed.
