### ISSUE TITLE
Error creating bots

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#131]
```!log
2021-01-22 14:27:52: Send invitations...
2021-01-22 14:27:52:  > Get dispatched lnuser... done (lucy.smith@wrcherieddixon26.xyz)
2021-01-22 14:28:18:  > Get dispatched results... done (10)
2021-01-22 14:28:24:  > Destroy browsers... Done
2021-01-22 14:28:24:  > Create proxy... 81.28.96.40:4033
2021-01-22 14:28:24:  > Create lnuser... ACEC7B99-59EF-4238-A931-A4A0BFD3693E
2021-01-22 14:28:24:  > Create browser (C067B0A0-85F8-4618-88A2-047412D51DDC)... Done
2021-01-22 14:28:34:  > Create Bot for Like A Post bot... done
2021-01-22 14:28:34:  > Create Bot for Search bot... done
2021-01-22 14:28:34:  > Create Bot for Invites bot... done
2021-01-22 14:28:34:  > Setup communication bot... done
2021-01-22 14:28:34:  > Setup confirm email bot... done
2021-01-22 14:28:34:  > Setup communication bot... done
2021-01-22 14:28:34:  > Creating Bot for Recovering... done
2021-01-22 14:32:38:  > Reporting failure Net::ReadTimeout. C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1384:in `request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:853:in `start'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1375:in `request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in `get'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/navigation.rb:30:in `to'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:77:in `goto'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.19/lib/browserfactory.rb:413:in `goto'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.14/lib/linkedin/bots/LinkedIn.rb:41:in `cookies_robot'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.14/lib/pampa/InInviteResultProcess.rb:432:in `process'
./p/botting.rb:110:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.17/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.19/lib/browserfactory.rb:247:in `run'
./p/botting.rb:151:in `<main>'... done
2021-01-22 14:32:39:  > Tracking bot error... done (with no screenshot)
2021-01-22 14:32:39:  > Ping to Division... Done
2021-01-22 14:32:51:  > Need to close browser?... yes
2021-01-22 14:32:51:  > Destroy browser... done
2021-01-22 14:33:28:  > Release lnuser... Done
2021-01-22 14:33:28: done
```

**Comment by leandrosardi** [comment]
Communication problems when operaring the Mimic browser.

Most probably it is a bottle neck in the mlalistener.

I have noticed that MLA lister is restaring very often.

**Comment by leandrosardi** [comment]
Done.
