### ISSUE TITLE
#bots error when scraping profile is harming the inchat process - new site design

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#227]
```log
Code: (unknown). unable to locate element, using {:class=>/inline t-24 t-black t-normal break-words/, :tag_name=>"li"}
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:536:in `assert_element_found'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:508:in `assert_exists'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:81:in `text'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.33/lib/linkedin/bots/LinkedInProfile.rb:64:in `scrape'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.33/lib/pampa/InChatResultProcess.rb:502:in `block in process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.33/lib/pampa/InChatResultProcess.rb:474:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.33/lib/pampa/InChatResultProcess.rb:474:in `process'
./p/botting.rb:98:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.20/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.29/lib/browserfactory.rb:251:in `run'
./p/botting.rb:151:in `<main>'
```

**Comment by leandrosardi** [comment]
Fixed.
