### ISSUE TITLE
#jobs - error processing workload

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#238]
```
2021-04-15 13:28:43: Load the worker... done
2021-04-15 13:28:44: Update current process... done
2021-04-15 13:28:45: Ping... done
2021-04-15 13:28:45: Say hello to your _planner.rb process!
2021-04-15 13:28:46: Distribute workload...
2021-04-15 13:28:54:  > distribute_workload.Client Peachy Leads (C4D39528-A1C8-4337-A544-EE03B0824F44)... error: NaN
Y:/lib/framework.rb:670:in `round'
Y:/lib/framework.rb:670:in `block in distribute_workload'
Y:/lib/framework.rb:658:in `each'
Y:/lib/framework.rb:658:in `distribute_workload'
./p/_jobs.rb:208:in `block in distribute_workload'
./p/_jobs.rb:206:in `each'
./p/_jobs.rb:206:in `distribute_workload'
./p/_jobs.rb:792:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.20/lib/mylocalprocess.rb:12
6:in `run'
./p/_jobs.rb:952:in `<main>'.
```

**Comment by leandrosardi** [comment]
Fixed.
