### ISSUE TITLE
#bug error scraping profile headline

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#239]
```
Code: (unknown). timed out after 180 seconds
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/wait.rb:44:in `until'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.37/lib/linkedin/bots/LinkedInProfile.rb:76:in `scrape'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.37/lib/pampa/InChatResultProcess.rb:503:in `block in process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.37/lib/pampa/InChatResultProcess.rb:475:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bots-1.2.37/lib/pampa/InChatResultProcess.rb:475:in `process'
./p/botting.rb:98:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.20/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.2.29/lib/browserfactory.rb:251:in `run'
./p/botting.rb:151:in `<main>'
```

**Comment by leandrosardi** [comment]
Fixed.
