### ISSUE TITLE
automation recovery failing, because there are pictures instead text

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#44]
```
scrape.inbox.rb username=tim.galewski@absentviolent.xyz name=unicorn01

lead:An	thony Parchment:... converation
scrape message 1
scrape message 2
error: unable to locate element, using {:class=>/msg-s-event-listitem__message-bubble/, :tag_name=>"div"}
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:536:in `assert_element_found'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:508:in `assert_exists'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/element.rb:81:in `text'
Z:/lib/linkedin/bots/LinkedInChat.rb:331:in `block (2 levels) in scrape_inbox'
Z:/lib/linkedin/bots/LinkedInChat.rb:289:in `each'
Z:/lib/linkedin/bots/LinkedInChat.rb:289:in `block in scrape_inbox'
Z:/lib/linkedin/bots/LinkedInChat.rb:205:in `each'
Z:/lib/linkedin/bots/LinkedInChat.rb:205:in `scrape_inbox'
Z:/cli/scrape.inbox.rb:116:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.16/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.1.37/lib/browserfactory.rb:52:in `run'
Z:/cli/scrape.inbox.rb:251:in `<main>'
2020-10-02 13:32:20: Sleep for long time. Click CTRL+C to exit and close any opened browser..
```

**Comment by leandrosardi** [comment]
https://ibb.co/T1VdxYr

**Comment by leandrosardi** [comment]
DONE!
