### ISSUE TITLE
automation recovery failing, because the contact card of the lead wasn't loaded because the conversation is too long and it's showing the bottom of the conversation

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#45]
```
+ scrape.inbox.rb username=margie.kanski@31mitzitkrug.xyz name=unicorn01

2020-10-02 13:41:25: Scrape inbox...
Email confirmation... no

lead:Leland Lo:... converation
error: timed out after 30 seconds
C:/Ruby22/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/wait.rb:44:in `until'
Z:/lib/linkedin/bots/LinkedInChat.rb:260:in `block in scrape_inbox'
Z:/lib/linkedin/bots/LinkedInChat.rb:205:in `each'
Z:/lib/linkedin/bots/LinkedInChat.rb:205:in `scrape_inbox'
Z:/cli/scrape.inbox.rb:116:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.16/lib/myremoteprocess.rb:103:in `run'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/stealth_browser_automation-1.1.37/lib/browserfactory.rb:52:in `run'
Z:/cli/scrape.inbox.rb:251:in `<main>'
2020-10-02 13:42:13: Sleep for long time. Click CTRL+C to exit and close any opened browser...
```

**Comment by leandrosardi** [comment]
DONE!
