### ISSUE TITLE
zapier integration query timeout alert

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#51]
´´´
"TinyTds::Error: Adaptive Server connection timed out<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:218:in `fields&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:218:in `block in fetch_rows&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:63:in `block in execute&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `block in synchronize&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/threaded.rb:103:in `hold&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `synchronize&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:32:in `execute&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:950:in `execute&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:217:in `fetch_rows&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:139:in `each&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:45:in `block in all&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:890:in `_all&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:45:in `all&#39;<br/>Y:/views/api1.5/2sm/get_latest_leads.erb:63:in `__tilt_22880172&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `render&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:667:in `erb&#39;<br/>app.rb:5042:in `block in &lt;main&gt;&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:252:in `context&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:247:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/logger.rb:15:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/commonlogger.rb:33:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-1.6.13/lib/rack/methodoverride.rb:22:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `call&#39;<br/>C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread&#39;"
´´´

**Comment by leandrosardi** [comment]
Replace this query:

```
select top 100 m.id_pipeline as pipeline_id, p.id as profile_id, p.name as profile_name, p.headline as profile_headline, p.location as profile_location, p.industry as profile_industry, 'https://linkedin.com/in/'+p.code as profile_linkedin_url
, min(h.inmessage_end_time) as first_transfer_date_time
, e.first_name as sales_assistant_first_name, e.last_name as sales_assistant_last_name
from client c with (nolock)
join [user] u with (nolock) on c.id=u.id_client
join [message] m with (nolock) on ( u.id=m.id_user and isnull(m.trigger_type,0) = 0 ) 
join lnchat i with (nolock) on m.id=i.id_message
join lnchat h with (nolock index(IX_lnchat__id_result__wlt_enabled__inmessage_end_time)) on (i.id_result = h.id_result and i.id_lnuser=h.id_lnuser and isnull(h.wlt_enabled,0)=1 and h.inmessage_end_time>=dateadd(WW, -2, getdate()))
join result r with (nolock) on r.id=i.id_result
join profile p with (nolock) on p.id=r.id_profile
join lnuser e with (nolock) on e.id=i.id_lnuser
where c.api_key = '56D608FC-645D-4A7B-9C38-94C853CADD5A'
and m.id_pipeline = '28C24049-146C-4182-A4C2-C2D0D408D59C'
group by m.id_pipeline, p.id, p.name, p.headline, p.location, p.industry, p.code, e.first_name, e.last_name
order by min(h.inmessage_end_time)
```

with this query:

```
select top 100 
	t.id_pipeline as pipeline_id, t.id_profile as profile_id, 
	p.name as profile_name, p.headline as profile_headline, p.location as profile_location, p.industry as profile_industry, 
	'https://linkedin.com/in/'+p.code as profile_linkedin_url
from drl_minutely_stats t
join client c on (c.id=t.id_client and c.api_key = '56D608FC-645D-4A7B-9C38-94C853CADD5A')
join [profile] p on p.id=t.id_profile
where t.id_pipeline = '28C24049-146C-4182-A4C2-C2D0D408D59C'
and t.wlt_time is not null
and t.wlt_time > DATEADD(WW,-2,GETDATE())
```

**Comment by leandrosardi** [comment]
DONE!

**Comment by leandrosardi** [comment]
DONE!
