### ISSUE TITLE
dispatcher.ininvte.result - Dynamic query syntax error. 

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/blackstack#97]
```
2021-01-06 22:36:18: botting.NEWTON02.00-50-56-04-F7-F7-33.unicorn20...
2021-01-06 22:36:18:  > starting job... done
2021-01-06 22:36:18:  > Client... Keep it Simple Business Solutions
2021-01-06 22:36:18:  > repair.lnuser... 0/5
2021-01-06 22:36:18:  > message.results... 0/3
2021-01-06 22:36:21:  > invite.results...
2021-01-06 22:36:25: Local Process Error: TinyTds::Error: Incorrect syntax nearthe keyword 'WHERE'.
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:218:in `fields'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:218:in `block in fetch_rows'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:63:in `block in execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `synchronize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:32:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:950:in `execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/tinytds.rb:217:in `fetch_rows'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:139:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:45:in `block in all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:890:in `_all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:45:in `all'
Y:/dispatchers/invite.result.rb:160:in `block (2 levels) in <top (required)>'
Y:/dispatchers/invite.result.rb:102:in `each'
Y:/dispatchers/invite.result.rb:102:in `block in <top (required)>'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_dispatcher-1.1.4/lib/pampa_dispatcher.rb:122:in `call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_dispatcher-1.1.4/lib/pampa_dispatcher.rb:122:in `selecting'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_dispatcher-1.1.4/lib/pampa_dispatcher.rb:196:in `run_dispatch'./p/dispatcher.rb:125:in `block in process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:892:in `each'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:892:in `_all'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:45:in `all'
./p/dispatcher.rb:72:in `process'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/pampa_workers-1.1.20/lib/mylocalprocess.rb:126:in `run'
./p/dispatcher.rb:254:in `<main>'
```

**Comment by leandrosardi** [comment]
Fixed!
